/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module alu_5 (
    input [17:0] a,
    input [17:0] b,
    input [5:0] alufn,
    output reg [17:0] out
  );
  
  
  
  wire [18-1:0] M_adder_out;
  adder_16 adder (
    .a(a),
    .b(b),
    .alufn(alufn),
    .out(M_adder_out)
  );
  wire [18-1:0] M_compare_out;
  compare_17 compare (
    .a(a),
    .b(b),
    .alufn(alufn),
    .out(M_compare_out)
  );
  
  always @* begin
    out = 1'h0;
    if (alufn == 6'h00 | alufn == 6'h01) begin
      out = M_adder_out;
    end else begin
      if (alufn == 6'h33 | alufn == 6'h35 | alufn == 6'h37) begin
        out = M_compare_out;
      end else begin
        out = 1'h0;
      end
    end
  end
endmodule
