/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module randomnum_13 (
    input clk,
    input [17:0] in,
    input rst,
    input submitbutton,
    output reg [17:0] out
  );
  
  
  
  wire [32-1:0] M_pn_gen_num;
  reg [1-1:0] M_pn_gen_next;
  reg [32-1:0] M_pn_gen_seed;
  pn_gen_30 pn_gen (
    .clk(clk),
    .rst(rst),
    .next(M_pn_gen_next),
    .seed(M_pn_gen_seed),
    .num(M_pn_gen_num)
  );
  
  always @* begin
    M_pn_gen_seed = 32'h000055a1;
    M_pn_gen_next = 1'h0;
    out = in;
    if (submitbutton) begin
      M_pn_gen_next = 1'h1;
      out[15+2-:3] = M_pn_gen_num[29+2-:3];
      out[12+2-:3] = M_pn_gen_num[26+2-:3];
      out[9+2-:3] = M_pn_gen_num[23+2-:3];
      out[6+2-:3] = M_pn_gen_num[20+2-:3];
      out[3+2-:3] = M_pn_gen_num[17+2-:3];
      out[0+2-:3] = M_pn_gen_num[15+2-:3];
      if (M_pn_gen_num[29+2-:3] == 3'h5) begin
        out[15+2-:3] = 3'h1;
      end
      if (M_pn_gen_num[29+2-:3] == 3'h6) begin
        out[15+2-:3] = 3'h2;
      end
      if (M_pn_gen_num[29+2-:3] == 3'h7) begin
        out[15+2-:3] = 3'h3;
      end
      if (M_pn_gen_num[26+2-:3] == 3'h5) begin
        out[12+2-:3] = 3'h1;
      end
      if (M_pn_gen_num[26+2-:3] == 3'h6) begin
        out[12+2-:3] = 3'h2;
      end
      if (M_pn_gen_num[26+2-:3] == 3'h7) begin
        out[12+2-:3] = 3'h3;
      end
      if (M_pn_gen_num[23+2-:3] == 3'h5) begin
        out[9+2-:3] = 3'h1;
      end
      if (M_pn_gen_num[23+2-:3] == 3'h6) begin
        out[9+2-:3] = 3'h2;
      end
      if (M_pn_gen_num[23+2-:3] == 3'h7) begin
        out[9+2-:3] = 3'h3;
      end
      if (M_pn_gen_num[20+2-:3] == 3'h5) begin
        out[6+2-:3] = 3'h1;
      end
      if (M_pn_gen_num[20+2-:3] == 3'h6) begin
        out[6+2-:3] = 3'h2;
      end
      if (M_pn_gen_num[20+2-:3] == 3'h7) begin
        out[6+2-:3] = 3'h3;
      end
      if (M_pn_gen_num[17+2-:3] == 3'h5) begin
        out[3+2-:3] = 3'h1;
      end
      if (M_pn_gen_num[17+2-:3] == 3'h6) begin
        out[3+2-:3] = 3'h2;
      end
      if (M_pn_gen_num[17+2-:3] == 3'h7) begin
        out[3+2-:3] = 3'h3;
      end
      if (M_pn_gen_num[15+2-:3] == 3'h5) begin
        out[0+2-:3] = 3'h1;
      end
      if (M_pn_gen_num[15+2-:3] == 3'h6) begin
        out[0+2-:3] = 3'h2;
      end
      if (M_pn_gen_num[15+2-:3] == 3'h7) begin
        out[0+2-:3] = 3'h3;
      end
      if (M_pn_gen_num[29+2-:3] == 3'h0) begin
        out[15+2-:3] = 3'h1;
      end
      if (M_pn_gen_num[26+2-:3] == 3'h0) begin
        out[12+2-:3] = 3'h2;
      end
      if (M_pn_gen_num[23+2-:3] == 3'h0) begin
        out[9+2-:3] = 3'h3;
      end
      if (M_pn_gen_num[20+2-:3] == 3'h0) begin
        out[6+2-:3] = 3'h2;
      end
      if (M_pn_gen_num[17+2-:3] == 3'h0) begin
        out[3+2-:3] = 3'h3;
      end
      if (M_pn_gen_num[15+2-:3] == 3'h0) begin
        out[0+2-:3] = 3'h4;
      end
      if (M_pn_gen_num[17+2-:3] == 3'h4) begin
        out[3+2-:3] = 3'h1;
      end
      if (M_pn_gen_num[0+1-:2] == 2'h1) begin
        out[15+2-:3] = 3'h0;
      end
      if (M_pn_gen_num[0+1-:2] == 2'h2) begin
        out[15+2-:3] = 3'h0;
        out[12+2-:3] = 3'h0;
      end
      if (M_pn_gen_num[0+1-:2] == 2'h3) begin
        out[15+2-:3] = 3'h0;
        out[12+2-:3] = 3'h0;
        out[9+2-:3] = 3'h0;
      end
    end
  end
endmodule
