/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module toled_2 (
    input [17:0] in,
    output reg [3:0] led1,
    output reg [3:0] led2,
    output reg [3:0] led3,
    output reg [3:0] led4,
    output reg [3:0] led5,
    output reg [3:0] led6
  );
  
  
  
  always @* begin
    led1 = 4'h0;
    led2 = 4'h0;
    led3 = 4'h0;
    led4 = 4'h0;
    led5 = 4'h0;
    led6 = 4'h0;
    if (in[0+2-:3] == 3'h0) begin
      led1 = 4'h0;
    end
    if (in[0+2-:3] == 3'h1) begin
      led1 = 4'h1;
    end
    if (in[0+2-:3] == 3'h2) begin
      led1 = 4'h2;
    end
    if (in[0+2-:3] == 3'h3) begin
      led1 = 4'h4;
    end
    if (in[0+2-:3] == 3'h4) begin
      led1 = 4'h8;
    end
    if (in[3+2-:3] == 3'h0) begin
      led2 = 4'h0;
    end
    if (in[3+2-:3] == 3'h1) begin
      led2 = 4'h1;
    end
    if (in[3+2-:3] == 3'h2) begin
      led2 = 4'h2;
    end
    if (in[3+2-:3] == 3'h3) begin
      led2 = 4'h4;
    end
    if (in[3+2-:3] == 3'h4) begin
      led2 = 4'h8;
    end
    if (in[6+2-:3] == 3'h0) begin
      led3 = 4'h0;
    end
    if (in[6+2-:3] == 3'h1) begin
      led3 = 4'h1;
    end
    if (in[6+2-:3] == 3'h2) begin
      led3 = 4'h2;
    end
    if (in[6+2-:3] == 3'h3) begin
      led3 = 4'h4;
    end
    if (in[6+2-:3] == 3'h4) begin
      led3 = 4'h8;
    end
    if (in[9+2-:3] == 3'h0) begin
      led4 = 4'h0;
    end
    if (in[9+2-:3] == 3'h1) begin
      led4 = 4'h1;
    end
    if (in[9+2-:3] == 3'h2) begin
      led4 = 4'h2;
    end
    if (in[9+2-:3] == 3'h3) begin
      led4 = 4'h4;
    end
    if (in[9+2-:3] == 3'h4) begin
      led4 = 4'h8;
    end
    if (in[12+2-:3] == 3'h0) begin
      led5 = 4'h0;
    end
    if (in[12+2-:3] == 3'h1) begin
      led5 = 4'h1;
    end
    if (in[12+2-:3] == 3'h2) begin
      led5 = 4'h2;
    end
    if (in[12+2-:3] == 3'h3) begin
      led5 = 4'h4;
    end
    if (in[12+2-:3] == 3'h4) begin
      led5 = 4'h8;
    end
    if (in[15+2-:3] == 3'h0) begin
      led6 = 4'h0;
    end
    if (in[15+2-:3] == 3'h1) begin
      led6 = 4'h1;
    end
    if (in[15+2-:3] == 3'h2) begin
      led6 = 4'h2;
    end
    if (in[15+2-:3] == 3'h3) begin
      led6 = 4'h4;
    end
    if (in[15+2-:3] == 3'h4) begin
      led6 = 4'h8;
    end
  end
endmodule
