/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module compare_17 (
    input [17:0] a,
    input [17:0] b,
    input [5:0] alufn,
    output reg [17:0] out
  );
  
  
  
  always @* begin
    out = 1'h0;
    
    case (alufn)
      6'h33: begin
        if (a == b) begin
          out[0+0-:1] = 1'h1;
        end
      end
      6'h35: begin
        if ($signed(a) < $signed(b)) begin
          out[0+0-:1] = 1'h1;
        end
      end
      6'h37: begin
        if ($signed(a) <= $signed(b)) begin
          out[0+0-:1] = 1'h1;
        end
      end
    endcase
  end
endmodule
