/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module userinput_dp_1 (
    input [17:0] in,
    input [2:0] layer,
    input rbutton,
    input bbutton,
    input gbutton,
    input ybutton,
    input undobutton,
    input submitbutton,
    output reg [17:0] out
  );
  
  
  
  always @* begin
    out = in;
    if (rbutton & layer == 1'h0) begin
      out[0+2-:3] = 3'h1;
    end
    if (gbutton & layer == 1'h0) begin
      out[0+2-:3] = 3'h2;
    end
    if (bbutton & layer == 1'h0) begin
      out[0+2-:3] = 3'h3;
    end
    if (ybutton & layer == 1'h0) begin
      out[0+2-:3] = 3'h4;
    end
    if (rbutton & layer == 1'h1) begin
      out[3+2-:3] = 3'h1;
    end
    if (gbutton & layer == 1'h1) begin
      out[3+2-:3] = 3'h2;
    end
    if (bbutton & layer == 1'h1) begin
      out[3+2-:3] = 3'h3;
    end
    if (ybutton & layer == 1'h1) begin
      out[3+2-:3] = 3'h4;
    end
    if (rbutton & layer == 2'h2) begin
      out[6+2-:3] = 3'h1;
    end
    if (gbutton & layer == 2'h2) begin
      out[6+2-:3] = 3'h2;
    end
    if (bbutton & layer == 2'h2) begin
      out[6+2-:3] = 3'h3;
    end
    if (ybutton & layer == 2'h2) begin
      out[6+2-:3] = 3'h4;
    end
    if (rbutton & layer == 2'h3) begin
      out[9+2-:3] = 3'h1;
    end
    if (gbutton & layer == 2'h3) begin
      out[9+2-:3] = 3'h2;
    end
    if (bbutton & layer == 2'h3) begin
      out[9+2-:3] = 3'h3;
    end
    if (ybutton & layer == 2'h3) begin
      out[9+2-:3] = 3'h4;
    end
    if (rbutton & layer == 3'h4) begin
      out[12+2-:3] = 3'h1;
    end
    if (gbutton & layer == 3'h4) begin
      out[12+2-:3] = 3'h2;
    end
    if (bbutton & layer == 3'h4) begin
      out[12+2-:3] = 3'h3;
    end
    if (ybutton & layer == 3'h4) begin
      out[12+2-:3] = 3'h4;
    end
    if (rbutton & layer == 3'h5) begin
      out[15+2-:3] = 3'h1;
    end
    if (gbutton & layer == 3'h5) begin
      out[15+2-:3] = 3'h2;
    end
    if (bbutton & layer == 3'h5) begin
      out[15+2-:3] = 3'h3;
    end
    if (ybutton & layer == 3'h5) begin
      out[15+2-:3] = 3'h4;
    end
    if (undobutton & layer == 1'h1) begin
      out[0+2-:3] = 3'h0;
    end
    if (undobutton & layer == 2'h2) begin
      out[3+2-:3] = 3'h0;
    end
    if (undobutton & layer == 2'h3) begin
      out[6+2-:3] = 3'h0;
    end
    if (undobutton & layer == 3'h4) begin
      out[9+2-:3] = 3'h0;
    end
    if (undobutton & layer == 3'h5) begin
      out[12+2-:3] = 3'h0;
    end
    if (undobutton & layer == 3'h6) begin
      out[15+2-:3] = 3'h0;
    end
    if (submitbutton) begin
      out = 18'h00000;
    end
  end
endmodule
